name: Pull Request
on:
  pull_request:
    branches:
    - master

jobs:
  job-which-fails:
    runs-on: ubuntu-latest
    steps:
    - run: exit 0

  job-which-succeeds:
    runs-on: ubuntu-latest
    steps:
    - run: exit 0

  testing:
    runs-on: ubuntu-latest
    if: always()
    needs: [ job-which-fails, job-which-succeeds ]
    steps:
    - uses: actions/checkout@v2
      with:
        path: mattermost-alertify
    - uses: ./
      with:
        mattermost_webhook: ${{ secrets.MATTERMOST_WEBHOOK }}
        git_token: ${{ secrets.GITHUB_TOKEN }}